version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d:ro
    networks:
      - db_network

  postgresql:
    image: postgres:latest
    container_name: postgresql_container
    restart: 'no'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init/postgresql:/docker-entrypoint-initdb.d:ro
    networks:
      - db_network

  firebird:
    image: jacobalberty/firebird:latest
    container_name: firebird_container
    restart: 'no'
    environment:
      ISC_PASSWORD: ${DB_PASSWORD}
      FIREBIRD_USER: ${DB_USER}
      FIREBIRD_PASSWORD: ${DB_PASSWORD}
      FIREBIRD_DATABASE: ${DB_NAME}
    ports:
      - "3050:3050"
    volumes:
      - firebird_data:/firebird/data
    networks:
      - db_network

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: 'no'
    ports:
      - "8080:8080"
    networks:
      - db_network
    depends_on:
      - mariadb
      - postgresql
      - firebird

volumes:
  mariadb_data:
  postgresql_data:
  firebird_data:

networks:
  db_network:
    driver: bridge
