-- =============================================================
-- DB Learning Lab — Firebird
-- Base de datos de ejemplo: Sistema Escolar
-- =============================================================
-- NOTA: Firebird no ejecuta scripts automáticamente al iniciar
-- el contenedor. Sigue las instrucciones del README para
-- cargar este script manualmente con el cliente isql.
-- =============================================================
-- Comando para ejecutar (ver README, sección Firebird):
--   docker exec -i firebird_container isql -user LABUSER \
--     -password labpass123 /firebird/data/LABDB \
--     < init/firebird/01-schema.sql
-- =============================================================

-- -------------------------------------------------------------
-- Tabla: alumnos
-- -------------------------------------------------------------
CREATE TABLE alumnos (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(60)  NOT NULL,
    apellido  VARCHAR(60)  NOT NULL,
    email     VARCHAR(100),
    fecha_nac DATE,
    ciudad    VARCHAR(60)
);

-- -------------------------------------------------------------
-- Tabla: cursos
-- -------------------------------------------------------------
CREATE TABLE cursos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion BLOB SUB_TYPE TEXT,
    creditos    SMALLINT DEFAULT 3
);

-- -------------------------------------------------------------
-- Tabla: matriculas (relación alumno ↔ curso)
-- -------------------------------------------------------------
CREATE TABLE matriculas (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id INTEGER NOT NULL,
    curso_id  INTEGER NOT NULL,
    fecha_alta DATE DEFAULT CURRENT_DATE,
    CONSTRAINT fk_mat_alumno FOREIGN KEY (alumno_id) REFERENCES alumnos(id),
    CONSTRAINT fk_mat_curso  FOREIGN KEY (curso_id)  REFERENCES cursos(id),
    CONSTRAINT uq_matricula  UNIQUE (alumno_id, curso_id)
);

-- -------------------------------------------------------------
-- Tabla: notas
-- -------------------------------------------------------------
CREATE TABLE notas (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id INTEGER     NOT NULL,
    evaluacion   VARCHAR(50) NOT NULL,
    nota         NUMERIC(4,2),
    CONSTRAINT fk_nota_mat  FOREIGN KEY (matricula_id) REFERENCES matriculas(id),
    CONSTRAINT chk_nota     CHECK (nota >= 0 AND nota <= 10)
);

-- =============================================================
-- Datos de ejemplo
-- =============================================================

INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Ana',    'García',    'ana.garcia@lab.local',     '2005-03-15', 'Madrid');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Luis',   'Martínez',  'luis.martinez@lab.local',  '2004-07-22', 'Barcelona');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Sofía',  'López',     'sofia.lopez@lab.local',    '2005-11-08', 'Valencia');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Carlos', 'Sánchez',   'carlos.sanchez@lab.local', '2006-01-30', 'Sevilla');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('María',  'Fernández', 'maria.fernandez@lab.local','2005-09-14', 'Bilbao');

INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Bases de Datos I',  'Fundamentos de SQL y diseño relacional', 4);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Programación Web',  'HTML, CSS y JavaScript básico',          3);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Redes y Sistemas',  'Conceptos de redes LAN/WAN',             3);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Matemáticas I',     'Álgebra y cálculo diferencial',          4);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Inglés Técnico',    'Vocabulario y comunicación técnica',     2);

INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (1, 1, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (1, 2, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (2, 1, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (2, 3, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (3, 2, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (3, 4, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (4, 1, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (4, 5, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (5, 3, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (5, 4, '2026-02-01');

INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Parcial 1', 7.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Parcial 2', 8.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Final',     7.80);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (2, 'Parcial 1', 6.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (2, 'Final',     6.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Parcial 1', 9.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Parcial 2', 8.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Final',     9.20);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (4, 'Parcial 1', 5.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (4, 'Final',     6.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Parcial 1', 7.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Parcial 2', 7.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Final',     7.30);

COMMIT;

-- =============================================================
-- Ejercicios sugeridos (Firebird — diferencias de sintaxis)
-- =============================================================
-- 1. Listar todos los alumnos:
--    SELECT * FROM alumnos ORDER BY apellido;
--
-- 2. Cursos por alumno (JOIN):
--    SELECT a.nombre, a.apellido, c.nombre AS curso
--    FROM alumnos a
--    JOIN matriculas m ON a.id = m.alumno_id
--    JOIN cursos c ON c.id = m.curso_id;
--
-- 3. Nota promedio por alumno:
--    SELECT a.nombre, a.apellido, ROUND(AVG(n.nota), 2) AS promedio
--    FROM alumnos a
--    JOIN matriculas m ON a.id = m.alumno_id
--    JOIN notas n ON n.matricula_id = m.id
--    GROUP BY a.id, a.nombre, a.apellido;
--
-- Diferencias clave respecto a MySQL/PostgreSQL:
--   - No existe IF NOT EXISTS en CREATE TABLE
--   - Los INSERT deben ir separados (no multi-row VALUES)
--   - Se requiere COMMIT explícito al finalizar
--   - BLOB SUB_TYPE TEXT en lugar de TEXT
