-- =============================================================
-- DB Learning Lab — Firebird
-- Base de datos de ejemplo: Sistema Escolar
-- =============================================================
-- El script start.sh / start.bat carga este archivo
-- automáticamente tras detectar que el schema no existe.
--
-- Si necesitas recargarlo manualmente:
--   docker exec -i firebird_container isql-fb \
--     -user $DB_USER -password $DB_PASSWORD \
--     /firebird/data/$DB_NAME \
--     < init/firebird/01-schema.sql
-- =============================================================

-- -------------------------------------------------------------
-- Tabla: alumnos
-- Diferencia Firebird: no existe IF NOT EXISTS → el reset
-- (reset.sh) elimina los volúmenes antes de volver a cargar.
-- -------------------------------------------------------------
CREATE TABLE alumnos (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(60)  NOT NULL,
    apellido  VARCHAR(60)  NOT NULL,
    email     VARCHAR(100) UNIQUE,           -- igual que MariaDB/PostgreSQL
    fecha_nac DATE,
    ciudad    VARCHAR(60)
);

-- -------------------------------------------------------------
-- Tabla: cursos
-- -------------------------------------------------------------
CREATE TABLE cursos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion BLOB SUB_TYPE TEXT,           -- TEXT no existe en Firebird
    creditos    SMALLINT DEFAULT 3
);

-- -------------------------------------------------------------
-- Tabla: matriculas (relación alumno ↔ curso)
-- -------------------------------------------------------------
CREATE TABLE matriculas (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id INTEGER NOT NULL,
    curso_id  INTEGER NOT NULL,
    fecha_alta DATE DEFAULT CURRENT_DATE,
    CONSTRAINT fk_mat_alumno FOREIGN KEY (alumno_id) REFERENCES alumnos(id),
    CONSTRAINT fk_mat_curso  FOREIGN KEY (curso_id)  REFERENCES cursos(id),
    CONSTRAINT uq_matricula  UNIQUE (alumno_id, curso_id)
);

-- -------------------------------------------------------------
-- Tabla: notas
-- -------------------------------------------------------------
CREATE TABLE notas (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id INTEGER     NOT NULL,
    evaluacion   VARCHAR(50) NOT NULL,
    nota         NUMERIC(4,2),
    CONSTRAINT fk_nota_mat  FOREIGN KEY (matricula_id) REFERENCES matriculas(id),
    CONSTRAINT chk_nota     CHECK (nota >= 0 AND nota <= 10)
);

-- =============================================================
-- Datos de ejemplo (8 alumnos con casos pedagógicos)
-- =============================================================
-- Casos incluidos intencionalmente:
--   • 2 alumnos sin email (NULL)   → enseña IS NULL / COALESCE
--   • 1 alumno sin ninguna matrícula (id=8) → LEFT JOIN devuelve NULL
--   • 1 curso sin alumnos (id=6)            → el otro lado del LEFT JOIN
--   • 2 alumnos de la misma ciudad          → GROUP BY con varios resultados
--   • Fechas de alta variadas               → ejercicios de rangos de fecha
--   • 1 matrícula sin notas (id=11)         → OUTER JOIN en notas
-- =============================================================

-- Diferencia Firebird: INSERT múltiple (multi-row VALUES) NO está soportado.
-- Cada fila necesita su propia sentencia INSERT.

INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Ana',     'García',    'ana.garcia@lab.local',     '2005-03-15', 'Madrid');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Luis',    'Martínez',  'luis.martinez@lab.local',  '2004-07-22', 'Barcelona');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Sofía',   'López',     'sofia.lopez@lab.local',    '2005-11-08', 'Valencia');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Carlos',  'Sánchez',   'carlos.sanchez@lab.local', '2006-01-30', 'Sevilla');
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('María',   'Fernández', 'maria.fernandez@lab.local','2005-09-14', 'Bilbao');
-- id=6: sin email → NULL pedagógico
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Pedro',   'Ruiz',      NULL,                       '2005-06-20', 'Madrid');
-- id=7: sin email ni fecha_nac → más NULLs
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Laura',   'Moreno',    NULL,                       NULL,         'Sevilla');
-- id=8: sin ninguna matrícula (para LEFT JOIN pedagógico)
INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Diego',   'Torres',    'diego.torres@lab.local',   '2006-03-10', 'Valencia');

INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Bases de Datos I',  'Fundamentos de SQL y diseño relacional', 4);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Programación Web',  'HTML, CSS y JavaScript básico',          3);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Redes y Sistemas',  'Conceptos de redes LAN/WAN',             3);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Matemáticas I',     'Álgebra y cálculo diferencial',          4);
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Inglés Técnico',    'Vocabulario y comunicación técnica',     2);
-- id=6: sin alumnos matriculados (para LEFT JOIN pedagógico)
INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Seguridad Informática', 'Fundamentos de ciberseguridad',      3);

-- Fechas variadas para ejercicios de rangos temporales
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (1, 1, '2026-01-15');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (1, 2, '2026-01-15');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (2, 1, '2026-01-20');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (2, 3, '2026-01-20');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (3, 2, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (3, 4, '2026-02-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (4, 1, '2026-02-10');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (4, 5, '2026-02-10');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (5, 3, '2026-02-15');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (5, 4, '2026-02-15');
-- id=11: matrícula sin notas (Pedro en BD I) → OUTER JOIN pedagógico
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (6, 1, '2026-03-01');
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES (7, 2, '2026-03-01');
-- id=8 (Diego) no tiene matrícula → alumno visible sólo con LEFT JOIN

INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Parcial 1', 7.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Parcial 2', 8.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (1, 'Final',     7.80);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (2, 'Parcial 1', 6.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (2, 'Final',     6.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Parcial 1', 9.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Parcial 2', 8.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (3, 'Final',     9.20);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (4, 'Parcial 1', 5.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (4, 'Final',     6.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Parcial 1', 7.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Parcial 2', 7.50);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (5, 'Final',     7.30);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (7, 'Parcial 1', 8.00);
INSERT INTO notas (matricula_id, evaluacion, nota) VALUES (7, 'Final',     8.50);
-- matrícula 11 (Pedro en BD I) queda sin notas → caso NULL en LEFT JOIN

COMMIT;

-- =============================================================
-- Ejercicios sugeridos (Firebird — diferencias de sintaxis)
-- =============================================================
-- Ver exercises/ para ejercicios estructurados por nivel.
--
-- Diferencias clave respecto a MySQL/PostgreSQL:
--   • No existe IF NOT EXISTS en CREATE TABLE
--   • Los INSERT deben ir separados (no multi-row VALUES)
--   • Se requiere COMMIT explícito al finalizar
--   • BLOB SUB_TYPE TEXT en lugar de TEXT
--   • LIMIT no existe → usar ROWS N o FETCH FIRST N ROWS ONLY
--   • Concatenación: || (igual que PostgreSQL, distinto de CONCAT())
--   • Usuario siempre en MAYÚSCULAS (LABUSER, no labuser)
