-- =============================================================
-- DB Learning Lab — MariaDB
-- Base de datos de ejemplo: Sistema Escolar
-- =============================================================
-- Tablas: alumnos, cursos, matriculas, notas
-- Ver exercises/ para ejercicios estructurados por nivel.
-- =============================================================

-- La base de datos activa es la definida en DB_NAME (.env).
-- Docker la selecciona automáticamente via MYSQL_DATABASE;
-- no es necesario (ni correcto) usar USE aquí.

-- -------------------------------------------------------------
-- Tabla: alumnos
-- AUTO_INCREMENT: sintaxis propia de MariaDB/MySQL
-- (PostgreSQL usa SERIAL; Firebird usa GENERATED BY DEFAULT AS IDENTITY)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alumnos (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    nombre     VARCHAR(60)  NOT NULL,
    apellido   VARCHAR(60)  NOT NULL,
    email      VARCHAR(100) UNIQUE,
    fecha_nac  DATE,
    ciudad     VARCHAR(60)
);

-- -------------------------------------------------------------
-- Tabla: cursos
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cursos (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion TEXT,
    creditos    TINYINT DEFAULT 3
);

-- -------------------------------------------------------------
-- Tabla: matriculas (relación alumno ↔ curso)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matriculas (
    id         INT  AUTO_INCREMENT PRIMARY KEY,
    alumno_id  INT  NOT NULL,
    curso_id   INT  NOT NULL,
    fecha_alta DATE DEFAULT (CURRENT_DATE),
    CONSTRAINT fk_mat_alumno FOREIGN KEY (alumno_id) REFERENCES alumnos(id),
    CONSTRAINT fk_mat_curso  FOREIGN KEY (curso_id)  REFERENCES cursos(id),
    UNIQUE KEY uq_matricula (alumno_id, curso_id)
);

-- -------------------------------------------------------------
-- Tabla: notas
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notas (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    matricula_id INT          NOT NULL,
    evaluacion   VARCHAR(50)  NOT NULL,
    nota         DECIMAL(4,2) CHECK (nota >= 0 AND nota <= 10),
    CONSTRAINT fk_nota_mat FOREIGN KEY (matricula_id) REFERENCES matriculas(id)
);

-- =============================================================
-- Datos de ejemplo (8 alumnos con casos pedagógicos)
-- =============================================================
-- Casos incluidos intencionalmente:
--   • 2 alumnos sin email (NULL)   → enseña IS NULL / COALESCE
--   • 1 alumno sin ninguna matrícula (id=8) → LEFT JOIN devuelve NULL
--   • 1 curso sin alumnos (id=6)            → el otro lado del LEFT JOIN
--   • 2 alumnos de la misma ciudad          → GROUP BY con varios resultados
--   • Fechas de alta variadas               → ejercicios de rangos de fecha
--   • 1 matrícula sin notas (id=11)         → OUTER JOIN en notas
-- =============================================================

INSERT INTO alumnos (nombre, apellido, email, fecha_nac, ciudad) VALUES
  ('Ana',    'García',    'ana.garcia@lab.local',     '2005-03-15', 'Madrid'),
  ('Luis',   'Martínez',  'luis.martinez@lab.local',  '2004-07-22', 'Barcelona'),
  ('Sofía',  'López',     'sofia.lopez@lab.local',    '2005-11-08', 'Valencia'),
  ('Carlos', 'Sánchez',   'carlos.sanchez@lab.local', '2006-01-30', 'Sevilla'),
  ('María',  'Fernández', 'maria.fernandez@lab.local','2005-09-14', 'Bilbao'),
  -- id=6: sin email → NULL pedagógico
  ('Pedro',  'Ruiz',      NULL,                       '2005-06-20', 'Madrid'),
  -- id=7: sin email ni fecha_nac → más NULLs
  ('Laura',  'Moreno',    NULL,                       NULL,         'Sevilla'),
  -- id=8: sin ninguna matrícula (para LEFT JOIN pedagógico)
  ('Diego',  'Torres',    'diego.torres@lab.local',   '2006-03-10', 'Valencia');

INSERT INTO cursos (nombre, descripcion, creditos) VALUES
  ('Bases de Datos I',      'Fundamentos de SQL y diseño relacional', 4),
  ('Programación Web',      'HTML, CSS y JavaScript básico',          3),
  ('Redes y Sistemas',      'Conceptos de redes LAN/WAN',             3),
  ('Matemáticas I',         'Álgebra y cálculo diferencial',          4),
  ('Inglés Técnico',        'Vocabulario y comunicación técnica',     2),
  -- id=6: sin alumnos matriculados (para LEFT JOIN pedagógico)
  ('Seguridad Informática', 'Fundamentos de ciberseguridad',          3);

-- Fechas variadas para ejercicios de rangos temporales
INSERT INTO matriculas (alumno_id, curso_id, fecha_alta) VALUES
  (1, 1, '2026-01-15'), (1, 2, '2026-01-15'),
  (2, 1, '2026-01-20'), (2, 3, '2026-01-20'),
  (3, 2, '2026-02-01'), (3, 4, '2026-02-01'),
  (4, 1, '2026-02-10'), (4, 5, '2026-02-10'),
  (5, 3, '2026-02-15'), (5, 4, '2026-02-15'),
  -- id=11: Pedro en BD I — sin notas (OUTER JOIN pedagógico)
  (6, 1, '2026-03-01'),
  (7, 2, '2026-03-01');
  -- id=8 (Diego) queda sin matrícula → visible sólo con LEFT JOIN

INSERT INTO notas (matricula_id, evaluacion, nota) VALUES
  (1, 'Parcial 1', 7.50), (1, 'Parcial 2', 8.00), (1, 'Final', 7.80),
  (2, 'Parcial 1', 6.00),                          (2, 'Final', 6.50),
  (3, 'Parcial 1', 9.00), (3, 'Parcial 2', 8.50), (3, 'Final', 9.20),
  (4, 'Parcial 1', 5.50),                          (4, 'Final', 6.00),
  (5, 'Parcial 1', 7.00), (5, 'Parcial 2', 7.50), (5, 'Final', 7.30),
  (7, 'Parcial 1', 8.00),                          (7, 'Final', 8.50);
  -- matrícula 11 (Pedro en BD I) queda sin notas → caso NULL en LEFT JOIN
