-- =============================================================
-- DB Learning Lab — Ejercicio 7: Comparación cross-engine
-- Nivel: Referencia rápida para docentes y alumnos avanzados
-- =============================================================
-- Misma consulta, tres dialectos SQL distintos.
-- Ejecuta cada bloque en el motor correspondiente.
-- =============================================================

-- =============================================================
-- 1. AUTO-INCREMENT: crear una tabla con clave primaria autogenerada
-- =============================================================

-- MariaDB:
CREATE TABLE IF NOT EXISTS demo (
    id    INT AUTO_INCREMENT PRIMARY KEY,
    valor VARCHAR(50)
);

-- PostgreSQL:
CREATE TABLE IF NOT EXISTS demo (
    id    SERIAL PRIMARY KEY,
    valor VARCHAR(50)
);
-- También válido en PostgreSQL 10+:
-- id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY

-- Firebird:
CREATE TABLE demo (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor VARCHAR(50)
);


-- =============================================================
-- 2. LÍMITE DE FILAS
-- =============================================================

-- MariaDB / PostgreSQL:
SELECT * FROM alumnos ORDER BY apellido LIMIT 3;

-- Firebird:
SELECT FIRST 3 * FROM alumnos ORDER BY apellido;
-- o bien (estándar SQL):
-- SELECT * FROM alumnos ORDER BY apellido FETCH FIRST 3 ROWS ONLY;


-- =============================================================
-- 3. CONCATENACIÓN DE CADENAS
-- =============================================================

-- MariaDB:
SELECT CONCAT(nombre, ' ', apellido) AS nombre_completo FROM alumnos;
-- También funciona en MariaDB: nombre || ' ' || apellido

-- PostgreSQL:
SELECT nombre || ' ' || apellido AS nombre_completo FROM alumnos;
-- También: CONCAT(nombre, ' ', apellido)

-- Firebird:
SELECT nombre || ' ' || apellido AS nombre_completo FROM alumnos;
-- CONCAT no existe en Firebird → usar ||


-- =============================================================
-- 4. FECHA ACTUAL
-- =============================================================

-- MariaDB:
SELECT CURDATE(), NOW();         -- fecha / fecha+hora
SELECT CURRENT_DATE;             -- también válido

-- PostgreSQL:
SELECT CURRENT_DATE, NOW();      -- CURDATE() no existe

-- Firebird:
SELECT CURRENT_DATE, CURRENT_TIMESTAMP FROM RDB$DATABASE;
-- En Firebird, toda SELECT necesita FROM. RDB$DATABASE es
-- una tabla del sistema con exactamente 1 fila.


-- =============================================================
-- 5. CAST (conversión de tipos)
-- =============================================================

-- MariaDB:
SELECT CAST(nota AS CHAR) FROM notas LIMIT 5;

-- PostgreSQL:
SELECT CAST(nota AS TEXT)  FROM notas LIMIT 5;
SELECT nota::TEXT          FROM notas LIMIT 5;   -- sintaxis abreviada de PG

-- Firebird:
SELECT CAST(nota AS VARCHAR(10)) FROM notas ROWS 5;


-- =============================================================
-- 6. MANEJO DE NULLs: COALESCE / IFNULL / NVL
-- =============================================================

-- MariaDB:
SELECT nombre, IFNULL(email, 'sin email') AS email FROM alumnos;
-- COALESCE también funciona en MariaDB:
SELECT nombre, COALESCE(email, 'sin email') AS email FROM alumnos;

-- PostgreSQL:
SELECT nombre, COALESCE(email, 'sin email') AS email FROM alumnos;
-- IFNULL no existe en PostgreSQL

-- Firebird:
SELECT nombre, COALESCE(email, 'sin email') AS email FROM alumnos;
-- NVL también funciona en Firebird: NVL(email, 'sin email')


-- =============================================================
-- 7. AGRUPACIÓN CON ROLLUP (subtotales)
-- =============================================================

-- MariaDB:
SELECT ciudad, COUNT(*) AS total
FROM alumnos
GROUP BY ciudad WITH ROLLUP;

-- PostgreSQL:
SELECT ciudad, COUNT(*) AS total
FROM alumnos
GROUP BY ROLLUP(ciudad);

-- Firebird 4:
SELECT ciudad, COUNT(*) AS total
FROM alumnos
GROUP BY ROLLUP(ciudad);
-- Nota: ROLLUP requiere Firebird 4+


-- =============================================================
-- 8. WINDOW FUNCTIONS (funciones de ventana)
-- Disponible en MariaDB 10.2+, PostgreSQL 8.4+, Firebird 3+
-- =============================================================

-- Ranking de alumnos por nota promedio:
SELECT
    a.nombre,
    a.apellido,
    ROUND(AVG(n.nota), 2) AS promedio,
    RANK() OVER (ORDER BY AVG(n.nota) DESC) AS ranking
FROM alumnos a
JOIN matriculas m ON a.id = m.alumno_id
JOIN notas n      ON n.matricula_id = m.id
GROUP BY a.id, a.nombre, a.apellido
ORDER BY ranking;

-- Sintaxis idéntica en los 3 motores.
-- FireBird: ROUND puede necesitar CAST; usar CAST(AVG(n.nota) AS NUMERIC(4,2))
